import type { IPCharacter } from '@/types/ip'

export const SCORE_THRESHOLDS = {
  excellent: 85,
  good: 70,
  average: 60,
} as const

export const IP_CHARACTERS: Record<string, IPCharacter> = {
  sleep: {
    id: 'sleep',
    name: '小恐龙',
    emoji: '💙',
    dimensionColor: '#A8D8FF',
    glowColor: '168,216,255',
    sceneImage: '图一.png',
    transitionVideo: 'T-01.mp4',
    goodVideo: 'S-01.mp4',
    badVideo: 'S-03.mp4',
    feedbackVideo: 'S-04.mp4',
  },
  diet: {
    id: 'diet',
    name: '龙猫',
    emoji: '🍕',
    dimensionColor: '#FFD4A8',
    glowColor: '255,212,168',
    sceneImage: '图二.png',
    transitionVideo: 'T-02.mp4',
    goodVideo: 'D-01.mp4',
    badVideo: 'D-03.mp4',
    feedbackVideo: 'D-04.mp4',
  },
  exercise: {
    id: 'exercise',
    name: '小怪兽',
    emoji: '💪',
    dimensionColor: '#A8FFB4',
    glowColor: '168,255,180',
    sceneImage: '图三.png',
    transitionVideo: 'T-03.mp4',
    goodVideo: 'E-01.mp4',
    badVideo: 'E-03.mp4',
    feedbackVideo: 'E-04.mp4',
  },
  stress: {
    id: 'stress',
    name: '无翼鸟',
    emoji: '💱',
    dimensionColor: '#FFB8D4',
    glowColor: '255,184,212',
    sceneImage: '图四.png',
    transitionVideo: 'T-04.mp4',
    goodVideo: 'P-01.mp4',
    badVideo: 'P-03.mp4',
    feedbackVideo: 'P-04.mp4',
  },
  risk: {
    id: 'risk',
    name: '两脚兽',
    emoji: '❤',
    dimensionColor: '#FFE8A8',
    glowColor: '255,232,168',
    sceneImage: '图五.png',
    transitionVideo: 'T-05.mp4',
    goodVideo: 'R-01.mp4',
    badVideo: 'R-03.mp4',
    feedbackVideo: 'R-04.mp4',
  },
}
